# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{ffi-libnet}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Postmodern"]
  s.date = %q{2010-05-09}
  s.description = %q{Ruby FFI bindings for libnet.}
  s.email = %q{postmodern.mod3@gmail.com}
  s.extra_rdoc_files = [
    "ChangeLog.md",
     "LICENSE.txt",
     "README.md"
  ]
  s.files = [
    ".gitignore",
     ".specopts",
     ".yardopts",
     "ChangeLog.md",
     "LICENSE.txt",
     "Manifest.txt",
     "README.md",
     "Rakefile",
     "lib/libnet.rb",
     "lib/libnet/context.rb",
     "lib/libnet/context_queue.rb",
     "lib/libnet/context_queue_descriptor.rb",
     "lib/libnet/ethernet_addr.rb",
     "lib/libnet/fddi_addr.rb",
     "lib/libnet/ffi.rb",
     "lib/libnet/headers/arp.rb",
     "lib/libnet/headers/bgp4.rb",
     "lib/libnet/headers/bgp4_notification.rb",
     "lib/libnet/headers/bpg4_open.rb",
     "lib/libnet/headers/cdp.rb",
     "lib/libnet/headers/cdp_value.rb",
     "lib/libnet/headers/dhcpv4.rb",
     "lib/libnet/headers/dnsv4.rb",
     "lib/libnet/headers/dnsv4_udp.rb",
     "lib/libnet/headers/ethernet.rb",
     "lib/libnet/headers/fddi.rb",
     "lib/libnet/headers/ieee_802/arp.rb",
     "lib/libnet/headers/ieee_802/eap.rb",
     "lib/libnet/headers/ieee_802/ethernet.rb",
     "lib/libnet/headers/ieee_802/llc.rb",
     "lib/libnet/headers/ieee_802/snap.rb",
     "lib/libnet/headers/ieee_802/vlan.rb",
     "lib/libnet/in6_addr.rb",
     "lib/libnet/port_list_chain.rb",
     "lib/libnet/protocol_block.rb",
     "lib/libnet/stats.rb",
     "lib/libnet/typedefs.rb",
     "lib/libnet/version.rb"
  ]
  s.has_rdoc = %q{yard}
  s.homepage = %q{http://github.com/sophsec/libnet-ffi}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{Ruby FFI bindings for libnet.}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<ffi>, [">= 0.4.0"])
      s.add_development_dependency(%q<rspec>, [">= 1.3.0"])
      s.add_development_dependency(%q<yard>, [">= 0.5.3"])
    else
      s.add_dependency(%q<ffi>, [">= 0.4.0"])
      s.add_dependency(%q<rspec>, [">= 1.3.0"])
      s.add_dependency(%q<yard>, [">= 0.5.3"])
    end
  else
    s.add_dependency(%q<ffi>, [">= 0.4.0"])
    s.add_dependency(%q<rspec>, [">= 1.3.0"])
    s.add_dependency(%q<yard>, [">= 0.5.3"])
  end
end

